Update flake.lock (#263)
* flake.lock: Update

Flake lock file updates:

• Updated input 'catppuccin':
    'github:catppuccin/nix/e973584' (2026-01-09)
  → 'github:catppuccin/nix/48e67b4' (2026-01-16)
• Updated input 'catppuccin/nixpkgs':
    'github:NixOS/nixpkgs/cad22e7' (2025-12-30)
  → 'github:NixOS/nixpkgs/1412caf' (2026-01-13)
• Updated input 'firefox-addons':
    'gitlab:rycee/nur-expressions/7e51745?dir=pkgs/firefox-addons' (2026-01-15)
  → 'gitlab:rycee/nur-expressions/b092ea4?dir=pkgs/firefox-addons' (2026-01-16)
• Updated input 'ghostty':
    'github:ghostty-org/ghostty/26e243a' (2026-01-15)
  → 'github:ghostty-org/ghostty/56237ef' (2026-01-16)
• Updated input 'hardware':
    'github:nixos/nixos-hardware/7297dfc' (2026-01-15)
  → 'github:nixos/nixos-hardware/cce68f4' (2026-01-16)
• Updated input 'home-manager':
    'github:nix-community/home-manager/d21bee5' (2026-01-16)
  → 'github:nix-community/home-manager/c47b2cc' (2026-01-16)
• Updated input 'neovim-nightly':
    'github:nix-community/neovim-nightly-overlay/46edfd3' (2026-01-16)
  → 'github:nix-community/neovim-nightly-overlay/8162203' (2026-01-17)
• Updated input 'neovim-nightly/neovim-src':
    'github:neovim/neovim/43339de' (2026-01-15)
  → 'github:neovim/neovim/03494ad' (2026-01-16)
• Updated input 'nixos-needsreboot':
    'https://codeberg.org/api/v1/repos/Mynacol/nixos-needsreboot/archive/b0bf333aa48ace2d47735cc50553a58a9403e0c8.tar.gz' (2026-01-09)
  → 'https://codeberg.org/api/v1/repos/Mynacol/nixos-needsreboot/archive/eafda229c3a88d2b13a07db359f7b47655e93497.tar.gz' (2026-01-16)
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/1412caf' (2026-01-13)
  → 'github:nixos/nixpkgs/e4bae1b' (2026-01-16)
• Updated input 'nixpkgs-master':
    'github:nixos/nixpkgs/8807adf' (2026-01-16)
  → 'github:nixos/nixpkgs/47cbf58' (2026-01-17)
• Updated input 'nixpkgs-unstable':
    'github:nixos/nixpkgs/1412caf' (2026-01-13)
  → 'github:nixos/nixpkgs/e4bae1b' (2026-01-16)
• Updated input 'nixpkgs-wayland':
    'github:nix-community/nixpkgs-wayland/c4dbce0' (2026-01-16)
  → 'github:nix-community/nixpkgs-wayland/ba68392' (2026-01-17)
• Updated input 'tdc':
    'github:pschmitt/tdc/0a79533' (2026-01-15)
  → 'github:pschmitt/tdc/0557217' (2026-01-16)
• Updated input 'wezterm':
    'github:wez/wezterm/f3602d2?dir=nix' (2026-01-15)
  → 'github:wez/wezterm/712400a?dir=nix' (2026-01-16)
• Updated input 'zen-browser':
    'github:0xc000022070/zen-browser-flake/06f61b4' (2026-01-14)
  → 'github:0xc000022070/zen-browser-flake/ec7eefd' (2026-01-17)

* Remove services.resolved.extraConfig:

The option definition `services.resolved.extraConfig` in common/network/dns.nix no longer has any effect; please remove it.

* mullvad-closest -> mullvad-compass

error: 'mullvad-closest' has been removed as it was unmaintained. Consider using 'mullvad-compass' instead.

* mullvad-compass is only in master

* sort + grammar fix

---------

Co-authored-by: Philipp Schmitt <philipp@schmitt.co>